name: stdb
channels:
  - conda-forge
  - apple

dependencies:
  # base
  - python=3.10
  - tensorflow-deps
  - pip
  - pycodestyle
  - mypy
  - pandas-stubs
  - types-PyYAML
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - scipy
  - xarray
  - dask
  - h3-py
  - matplotlib
  - seaborn
  - click
  - pytables
  - pandas-gbq
  - gcsfs
  # geo
  - geojson
  - shapely
  - geopandas
  - affine
  - rasterio
  - rioxarray
  - earthengine-api
  - twine
  - sphinx
  - mystmd
  - myst-parser
  - jupyterlab-myst
  - altair-all
  - vega_datasets
  # -------------------
  - xarray-datatree
  - zarr
  # experimental vis
  - hvplot
  - bokeh
  - shiny
  - plotly
  - ipywidgets
  - jupyter-dash
  - types-requests
  - pip:
    - tensorflow-macos
    - tensorflow-metal
    - python-geohash
    - xee
    - build
    - mproc
