[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "spectral_trend_database"
version = "0.0.1"
readme = "README.md"
dependencies = []

[tool.setuptools]
packages = [
	"spectral_trend_database"
]