shared_config: jobs/config/shared.yaml
jobs:
    - name: j1
      file: jobs/modules/j1.py
      config: jobs/config/j1.yaml
    # if config is string import from file
    - name: j2
      file: jobs/modules/j2.py
      config: jobs/config/j2.yaml
    # no config is required
    - name: j3
      file: jobs/modules/j3.py
    # jobs without `file` run pre-defined jobs from stdb
    - name: j4