root_dir: /users/repo/root/dir
config_folder: if/exists/append/config/paths/below
user_config: path/to/user_config.yaml
indices_config: path/to/spectral_index_config.yaml
job_folder: jobs/
jobs:
    - name: j1
      file: jobs/modules/j1.py
      config:
        var1: 1
        var2: 123
    # if config is string import from file
    - name: j2
      file: jobs/modules/j2.py
      config: jobs/config/j2.yaml
    # no config is required
    - name: j3
      file: jobs/modules/j3.py
    # jobs without `file` run pre-defined jobs from stdb
    - name: j4