# ---------------------------------------------------------
#
# EXAMPLE USER CONFIG:
#
# A yaml configuration file to be used in scripts and modules.
# This is a location to provide local/user specific config, as
# well as a place to overwrite the constants found in:
#
#         spectral_trend_database/constants.py
#
# USAGE:
#
#   - copy file: `cp config/user.example.yaml config/user.yaml`
#   - delete the word "EXAMPLE" from comment line 3
#   - update required keys (see below) as needed
#   - check `spectral_trend_database/constants.py` to see if
#     any of those constants need to be overwritten.
#   - IMPORTANT NOTE: `config/user.yaml` will not be tracked by git.yaml
#
# REQUIRED KEYS:
#
# - ROOT_DIR
# - LOCAL_DATA_DIR
# - GCS_BUCKET
# - GCS_ROOT_FOLDER
# - UNIQUE_GEOHASH
# - MIN_REQUIRED_YEARS
# - SEARCH
# - SRC_GCS_BIOMASS_YIELD
# - SRC_LOCAL_US_COUNTIES_SHP
# - DEST_NAME
# - DEST_LOCAL_FOLDER
# - DEST_GCS_FOLDER
#
# ---------------------------------------------------------

# general
GCP_PROJECT: dse-regenag
ROOT_DIR: /UPDATE-ME/to/root/dir/of/project_folder
LOCAL_DATA_DIR: data/v1/qdann
GCS_BUCKET: agriculture_monitoring
GCS_ROOT_FOLDER: spectral_trend_database/v1/qdann
RAW_LOCAL_FOLDER: raw/biomass_landsat
RAW_GCS_FOLDER: raw/biomass_landsat
DEST_LOCAL_FOLDER: processed/biomass_landsat
DEST_GCS_FOLDER: processed/biomass_landsat
MAX_PROCESSES: 15
SAMPLE_POINTS_TABLE_NAME: sample_points

# step-0.export_landsat_yield_data
RAW_BASE_NAME: biomass_yield.2000-2022

# step-1.preprocess_raw_data
UNIQUE_GEOHASH: geohash_7
MIN_REQUIRED_YEARS: 6
SEARCH: b0-20\d{2}\.json$

SRC_GCS_BIOMASS_YIELD: raw/biomass_landsat
SRC_LOCAL_US_COUNTIES_SHP: src/cb_2023_us_county_500k
DEST_BIOMASS_YIELD_NAME: biomass_yield.2000-2022.b0.json

# step-2/3 bigquery_tables
DATASET_NAME: BiomassYieldTrends
LOCATION: US
RAW_INDICES_FOLDER: raw_indices
RAW_LANDSAT_QUERY: raw_landsat

# step-4: smoothing
MASK_EQ: ndvi > 0
SG_CONFIG:
  polyorder: 3
  window_length: 60
COORD_COLUMN: date
META_COLUMNS:
  - sample_id
  - year
RAW_INDEX_TABLE_NAME: raw_indices_v1
SMOOTHED_INDICES_TABLE_NAME: smoothed_indices_v1
SMOOTHED_INDICES_FOLDER: smoothed_indices
INDICES_STATS_TABLE_NAME: indices_stats_v1
INDICES_STATS_FOLDER: indices_stats

# step-5: cover-crop-features
MACD_TABLE_NAME: macd_indices_v1
MACD_FOLDER: macd
