# ---------------------------------------------------------
#
# EXAMPLE USER CONFIG:
#
# A yaml configuration file to be used in scripts and modules.
# This is a location to provide local/user specific config, as
# well as a place to overwrite the constants found in:
#     
#         spectral_trend_database/constants.py
#
# USAGE:
#
#   - copy file: `cp config/user.example.yaml config/user.yaml`
#   - delete the word "EXAMPLE" from comment line 3
#   - update required keys (see below) as needed
#   - check `spectral_trend_database/constants.py` to see if
#     any of those constants need to be overwritten.
#   - IMPORTANT NOTE: `config/user.yaml` will not be tracked by git.yaml
#
# REQUIRED KEYS:
#
# - ROOT_DIR
# - LOCAL_DATA_DIR
# - GCS_BUCKET
# - GCS_ROOT_FOLDER
# - UNIQUE_GEOHASH
# - MIN_REQUIRED_YEARS
# - SEARCH
# - SRC_GCS_BIOMASS_YIELD
# - SRC_LOCAL_US_COUNTIES_SHP
# - DEST_NAME
# - DEST_LOCAL_FOLDER
# - DEST_GCS_FOLDER
#
# ---------------------------------------------------------

# general
ROOT_DIR: /UPDATE-ME/to/root/dir/of/project_folder
LOCAL_DATA_DIR: data
GCS_BUCKET: agriculture_monitoring
GCS_ROOT_FOLDER: spectral_trend_database/v1

# step-1.preprocess_raw_data
UNIQUE_GEOHASH: geohash_7
MIN_REQUIRED_YEARS: 6
SEARCH: b0-20\d{2}\.csv$

SRC_GCS_BIOMASS_YIELD: biomass_landsat
SRC_LOCAL_US_COUNTIES_SHP: src/cb_2023_us_county_500k
DEST_NAME: biomass_yield.2000-2022.b0.json
DEST_LOCAL_FOLDER: processed/biomass_landsat
DEST_GCS_FOLDER: processed/biomass_landsat

