# ---------------------------------------------------------
#
# EXAMPLE USER CONFIG:
#
# A yaml configuration file to be used in scripts and modules.
# This is a location to provide local/user specific config, as
# well as a place to overwrite the constants found in:
#
#         spectral_trend_database/constants.py
#
# USAGE:
#
#   - copy file: `cp config/user.example.yaml config/user.yaml`
#   - delete the word "EXAMPLE" from comment line 3
#   - update required keys (see below) as needed
#   - check `spectral_trend_database/constants.py` to see if
#     any of those constants need to be overwritten.
#   - IMPORTANT NOTE: `config/user.yaml` will not be tracked by git.yaml
#
# REQUIRED KEYS:
#
# ---------------------------------------------------------


#
# LOCAL
#
ROOT_DIR: /UPDATE-ME/to/root/dir/of/project_folder
LOCAL_DATA_DIR: data/v1/qdann


#
# GCP
#
GCP_PROJECT: dse-regenag
GCS_BUCKET: agriculture_monitoring
GCS_ROOT_FOLDER: spectral_trend_database/v1/qdann
DEST_GCS_FOLDER: processed/biomass_landsat
DATASET_NAME: SpectralTrendDatabase
LOCATION: US


#
# US BOUNDARIES
# ----
# us-boundaries-reference:
# https://catalog.data.gov/dataset/2023-cartographic-boundary-file-shp-county-and-equivalent-for-united-states-1-500000
# ----
US_BOUNDARIES_URL: https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_county_500k.zip
US_BOUNDARIES_SHP: src/cb_2023_us_county_500k


#
# FOLDERS/FILES/TABLES
#
RAW_GCS_FOLDER: raw/biomass_landsat
RAW_LANDSAT_FILENAME: landsat
RAW_LANDSAT_FOLDER: landsat_raw_masked
QDANN_YIELD_TABLE_NAME: qdann_yield
QDANN_YIELD_FOLDER: qdann_yield
CROP_TYPE_TABLE_NAME: cdl_crop_type
CROP_TYPE_FOLDER: crop_type
SAMPLE_POINTS_TABLE_NAME: sample_points
YIELD_TABLE_NAME: qdann_yield
RAW_INDICES_TABLE_NAME: raw_indices_v1
RAW_INDICES_FOLDER: raw_indices
SMOOTHED_INDICES_TABLE_NAME: smoothed_indices_v1
SMOOTHED_INDICES_FOLDER: smoothed_indices
INDICES_STATS_TABLE_NAME: indices_stats_v1
INDICES_STATS_FOLDER: indices_stats
MACD_TABLE_NAME: macd_indices_v1
MACD_FOLDER: macd


#
# DATES
#
YEARS:
  - 2000
  - 2022
OFF_SEASON_START_YYMM: 12-01
OFF_SEASON_END_YYMM: 03-15
GROWING_SEASON_START_YYMM: 04-15
GROWING_SEASON_END_YYMM: 11-01


#
# CONFIG INTS
#
MAX_PROCESSES: 15
YIELD_BUFFER_RADIUS: 60
LANDSAT_BUFFER_RADIUS: 60
UNIQUE_H3: 7
MIN_REQUIRED_YEARS: 6
SG_CONFIG:
  polyorder: 3
  window_length: 60
