project: dse-regenag
dataset: BiomassTrends
defaults:
    using: sample_id
queries:
  raw_landsat:
    init:
        table: SAMPLE_POINTS
    join:
        table: LANDSAT_RAW_MASKED
  scym_raw_landsat:
    init:
        table: SAMPLE_POINTS
    join:
        - table: SCYM_YIELD
        - table: LANDSAT_RAW_MASKED
          using: sample_id, year