project: dse-regenag
dataset: BiomassTrends
defaults:
  how: LEFT
  select: '*'
  using: sample_id
queries:
  raw_landsat:
    table: SAMPLE_POINTS
    join:
    - table: LANDSAT_RAW_MASKED
    where:
    - key: year
      table: LANDSAT_RAW_MASKED
  scym_raw_landsat:
    table: SAMPLE_POINTS
    join:
    - table: SCYM_YIELD
    - table: LANDSAT_RAW_MASKED
      using: sample_id, year
    where:
    - key: year
      table: SCYM_YIELD

